---
# Create the vpc, subnets, security groups, etc
- name: "Create supporting vpc infrastructure"
  include: create-vpc.yml

# build each ec2 instance
- name: "Build ec2 instance"
  include: create-ec2.yml
  with_dict: "{{ moba_instances }}"
  loop_control:
    loop_var: instance