---
- name: "{{ application_name }} | Ensure {{ application_group }} group exists"
  group:
    name: "{{ application_group }}"

- name: "{ application_name }} | Ensure {{ application_user }} user exists"
  user:
    name: "{{ application_user }}"
    group: "{{ application_group }}"
    shell: /bin/bash

- name: "{{ application_name }} | Ensure main {{ application_name }} root dirs exists"
  file:
    path: "{{ item }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ application_home_dir }}"

- name: "{{ application_name }} | Check if {{ application_name }} installed"
  stat:
    path: "{{ application_configuration_file }}"
  register: application_installed_check

# Example for a zip file binary to download and extract
- name: "{{ application_name }} | Download into {{ application_download_dir }}"
  get_url:
    url: "{{ remote_binary_url }}/{{ application_package }}"
    dest: "{{ application_download_dir }}"
    url_username: "{{ application_remote_binary_username }}"
    url_password: "{{ aaplication_remote_binary_password }}"
  register: application_download
  when: not application_installed_check.stat.exists

- name: "{{ application_name }} | Unarchive into {{ application_install_dir }}"
  unarchive:
    src: "{{ application_download_dir }}"
    dest: "{{ application_install_dir }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    remote_src: yes
  register: application_download
  when: not application_installed_check.stat.exists


# # Example for a RPM binary to setup remote repo
# - name: Set up RPM remote repo
#   yum_repository:
#     name: epel
#     description: EPEL YUM repo
#     baseurl: "{{ artifactory_repo_url }}"
#     username: "{{ application_remote_binary_username }}"
#     password: "{{ application_remote_binary_password }}"
#     sslverify: no
#     gpgcheck: 0
#
# # Example for a yum install, once the remote repo is setup
# - name: "Install {{ application_name }}"
#   yum:
#     name: {{ application_name }}
#     state: present
